using System.Collections.Generic;
using BlacktideRequiem.Core.Data;

namespace BlacktideRequiem.Core.Combat
{
    /// <summary>
    /// Describes one active synergy: which trait activated, from which captain source,
    /// and the buff instances to apply.
    /// </summary>
    public class ActiveSynergy
    {
        /// <summary>The trait that activated this synergy.</summary>
        public TraitData Trait;

        /// <summary>Whether this activation came from the primary or second captain.</summary>
        public CaptainSource Source;

        /// <summary>Buff instances to inject into each qualifying combatant's BuffStack.</summary>
        public List<SynergyBuff> Buffs = new();
    }

    /// <summary>
    /// A single buff generated by synergy activation, targeting a specific combatant.
    /// </summary>
    public struct SynergyBuff
    {
        public CombatantState Target;
        public BuffInstance Buff;
    }

    /// <summary>
    /// Identifies which captain triggered a synergy activation.
    /// </summary>
    public enum CaptainSource
    {
        Primary,
        Secondary
    }

    /// <summary>
    /// Pure static evaluator for trait synergies. No state — call Evaluate each time
    /// synergies need (re-)calculation.
    ///
    /// Rules from Traits/Sinergias GDD:
    /// - Only captain's traits are checked for activation
    /// - Threshold: 3+ allies sharing the trait (including captains)
    /// - Per-unit bonus values (not global)
    /// - Buffs are permanent, non-dispellable
    /// - Friend guest = second captain (independent evaluation)
    /// - Double activation when both captains share a trait
    /// </summary>
    public static class SynergyEvaluator
    {
        /// <summary>Minimum allies sharing a captain's trait to activate synergy.</summary>
        public const int SYNERGY_THRESHOLD = 3;

        /// <summary>Source ability ID tagged on synergy buff instances.</summary>
        public const string SYNERGY_BUFF_SOURCE = "synergy";

        /// <summary>
        /// Evaluates all synergies for a team composition.
        /// Returns list of active synergies with buff instances ready to apply.
        /// </summary>
        /// <param name="allies">All ally combatant states (including guest).</param>
        /// <param name="captainIndex">Index of the primary captain in allies list.</param>
        /// <param name="isGuestFriend">Whether the last ally is a friend unit (second captain).</param>
        public static List<ActiveSynergy> Evaluate(
            IReadOnlyList<CombatantState> allies,
            int captainIndex,
            bool isGuestFriend)
        {
            var results = new List<ActiveSynergy>();

            if (allies == null || allies.Count == 0) return results;
            if (captainIndex < 0 || captainIndex >= allies.Count) return results;

            var primaryCaptain = allies[captainIndex];

            // Primary captain evaluation
            EvaluateCaptain(allies, primaryCaptain, CaptainSource.Primary, results);

            // Second captain evaluation (friend unit = last ally)
            if (isGuestFriend && allies.Count > 1)
            {
                var secondCaptain = allies[allies.Count - 1];
                EvaluateCaptain(allies, secondCaptain, CaptainSource.Secondary, results);
            }

            return results;
        }

        /// <summary>
        /// Evaluates all synergies for an enemy group.
        /// Returns list of active synergies with buff instances ready to apply.
        /// </summary>
        /// <param name="enemies">All enemy combatant states in the wave.</param>
        /// <param name="captainIndex">Index of the enemy captain (-1 = no captain).</param>
        public static List<ActiveSynergy> EvaluateEnemies(
            IReadOnlyList<CombatantState> enemies,
            int captainIndex)
        {
            var results = new List<ActiveSynergy>();

            if (enemies == null || enemies.Count == 0) return results;
            if (captainIndex < 0 || captainIndex >= enemies.Count) return results;

            var captain = enemies[captainIndex];
            EvaluateCaptain(enemies, captain, CaptainSource.Primary, results);

            return results;
        }

        /// <summary>
        /// Evaluates a single captain's traits against a team.
        /// </summary>
        private static void EvaluateCaptain(
            IReadOnlyList<CombatantState> team,
            CombatantState captain,
            CaptainSource source,
            List<ActiveSynergy> results)
        {
            if (captain.Template == null) return;
            var captainTraits = captain.Template.Traits;
            if (captainTraits == null) return;

            for (int t = 0; t < captainTraits.Count; t++)
            {
                var traitEntry = captainTraits[t];
                if (traitEntry.Trait == null) continue;

                string traitId = traitEntry.Trait.TraitId;

                // Count allies sharing this trait
                int matchCount = 0;
                for (int i = 0; i < team.Count; i++)
                {
                    if (HasTrait(team[i], traitId))
                        matchCount++;
                }

                if (matchCount < SYNERGY_THRESHOLD) continue;

                // Synergy activates — build buff list
                var synergy = new ActiveSynergy
                {
                    Trait = traitEntry.Trait,
                    Source = source
                };

                for (int i = 0; i < team.Count; i++)
                {
                    var unitTraitEntry = GetTraitEntry(team[i], traitId);
                    if (unitTraitEntry == null) continue;

                    var bonuses = unitTraitEntry.Value.SynergyBonus;
                    if (bonuses == null) continue;

                    for (int b = 0; b < bonuses.Count; b++)
                    {
                        var mod = bonuses[b];
                        var buff = new BuffInstance
                        {
                            StatAffected = mod.Stat,
                            Percentage = mod.Percent,
                            RemainingTurns = -1, // permanent
                            SourceAbilityId = SYNERGY_BUFF_SOURCE,
                            IsDispellable = false
                        };

                        synergy.Buffs.Add(new SynergyBuff
                        {
                            Target = team[i],
                            Buff = buff
                        });
                    }
                }

                results.Add(synergy);
            }
        }

        /// <summary>
        /// Checks if a combatant has a trait by ID.
        /// </summary>
        private static bool HasTrait(CombatantState combatant, string traitId)
        {
            if (combatant.Template == null) return false;
            var traits = combatant.Template.Traits;
            if (traits == null) return false;

            for (int i = 0; i < traits.Count; i++)
            {
                if (traits[i].Trait != null && traits[i].Trait.TraitId == traitId)
                    return true;
            }
            return false;
        }

        /// <summary>
        /// Gets the UnitTraitEntry for a specific trait on a combatant, or null if not found.
        /// </summary>
        private static UnitTraitEntry? GetTraitEntry(CombatantState combatant, string traitId)
        {
            if (combatant.Template == null) return null;
            var traits = combatant.Template.Traits;
            if (traits == null) return null;

            for (int i = 0; i < traits.Count; i++)
            {
                if (traits[i].Trait != null && traits[i].Trait.TraitId == traitId)
                    return traits[i];
            }
            return null;
        }

        /// <summary>
        /// Applies all buffs from a list of active synergies to combatant BuffStacks.
        /// </summary>
        public static void ApplyBuffs(List<ActiveSynergy> synergies)
        {
            if (synergies == null) return;

            for (int s = 0; s < synergies.Count; s++)
            {
                var buffs = synergies[s].Buffs;
                for (int b = 0; b < buffs.Count; b++)
                {
                    buffs[b].Target.Buffs.Add(buffs[b].Buff);
                }
            }
        }

        /// <summary>
        /// Removes all synergy buffs from combatant BuffStacks for a given list of synergies.
        /// </summary>
        public static void RemoveBuffs(List<ActiveSynergy> synergies)
        {
            if (synergies == null) return;

            for (int s = 0; s < synergies.Count; s++)
            {
                var buffs = synergies[s].Buffs;
                for (int b = 0; b < buffs.Count; b++)
                {
                    RemoveSynergyBuff(buffs[b].Target, buffs[b].Buff);
                }
            }
        }

        /// <summary>
        /// Removes a specific buff instance from a combatant's BuffStack by reference equality.
        /// </summary>
        private static void RemoveSynergyBuff(CombatantState target, BuffInstance buff)
        {
            // BuffInstance is a class — reference equality works
            var allBuffs = target.Buffs.All;
            for (int i = allBuffs.Count - 1; i >= 0; i--)
            {
                if (ReferenceEquals(allBuffs[i], buff))
                {
                    target.Buffs.RemoveAt(i);
                    return;
                }
            }
        }
    }
}
